"""
knowledge/skin_conditions.py — Static, deterministic guidance content for
MedScan AI's dermatology-assistant layer.

Everything in this file is hand-written, general dermatology-education
content — NOT generated by a model, NOT personalized medical advice, and
NOT a diagnosis. It exists specifically so the app.py result page and any
future RAG/assistant layer have safe, reviewed text to draw from instead of
letting an LLM invent medical claims (see config.CLASS_NAMES / the project's
own safety rules).

Three lookup tables:
  1. GUIDANCE_BY_SCREENING_RESULT — keyed by the model's actual binary output
     (config.CLASS_NAMES: "benign-pattern" / "suspicious-pattern"). This is
     the only table tied to the model's prediction.
  2. SKIN_KNOWLEDGE_CENTER — general educational topics, not tied to any
     scan result. Independent, browsable content.
  3. INGREDIENT_EXPLAINER — general skincare-ingredient education.

Every entry that recommends or discourages an action includes a "why".
Nothing here claims to know the user's actual diagnosis, cause, or the
right treatment for them — every section defers to professional evaluation
for anything beyond general education.
"""

DISCLAIMER = (
    "This information is educational and general in nature. It is not a "
    "diagnosis, and it does not replace evaluation by a qualified "
    "healthcare professional or dermatologist."
)

# ---------------------------------------------------------------------------
# 1. Guidance keyed to the model's actual binary screening output.
#    Keys MUST match config.CLASS_NAMES exactly.
# ---------------------------------------------------------------------------
GUIDANCE_BY_SCREENING_RESULT = {
    "suspicious-pattern": {
        "summary": (
            "The model detected visual patterns that are associated with "
            "higher-risk skin lesions in the training data. This is a "
            "screening signal, not a diagnosis — only a dermatologist can "
            "determine what a lesion actually is."
        ),
        "what_happens_in_skin": (
            "Skin lesions can change in size, shape, color, or texture for "
            "many reasons — some entirely benign (like sun exposure, aging, "
            "or minor irritation) and some that need professional evaluation "
            "(like abnormal cell growth). Visual pattern alone cannot "
            "distinguish between these causes; that requires clinical "
            "examination and, often, a biopsy."
        ),
        "contributing_factors": [
            {"factor": "UV / sun exposure", "note": "Cumulative sun exposure is a well-established factor in many skin changes over time."},
            {"factor": "Genetics / family history", "note": "Skin type and family history influence how skin ages and reacts to the environment."},
            {"factor": "Friction or repeated irritation", "note": "Areas under repeated rubbing or pressure can show visible changes."},
            {"factor": "Age-related skin changes", "note": "New or changing spots become more common with age, most of which are benign."},
            {"factor": "Prior skin injury", "note": "Scarring or pigment changes can follow earlier cuts, burns, or irritation."},
        ],
        "avoid": [
            {"action": "Avoid picking, scratching, or attempting to remove the lesion yourself",
             "why": "Mechanical irritation can cause bleeding, secondary infection, and scarring, and can also make it harder for a dermatologist to assess the lesion's original appearance."},
            {"action": "Avoid unregulated 'mole removal' creams or home remedies",
             "why": "These are not proven safe or effective and can delay proper evaluation or damage surrounding skin."},
            {"action": "Avoid unnecessary delay before professional evaluation",
             "why": "Even when a change turns out to be benign, timely evaluation is the only way to know that with confidence."},
        ],
        "general_care": [
            {"action": "Photograph the area under consistent lighting for your own records",
             "why": "A dated photo makes it easier for you or a dermatologist to judge whether something has changed."},
            {"action": "Use broad-spectrum sunscreen on exposed skin",
             "why": "Reducing further UV exposure is a reasonable general precaution while awaiting evaluation."},
            {"action": "Avoid unnecessary friction or covering the area with tight clothing/jewelry",
             "why": "Reduces irritation while you arrange an evaluation."},
        ],
        "management_approaches": [
            "Dermatologists typically start with a clinical (in-person or dermatoscopic) examination.",
            "Depending on what they observe, they may recommend monitoring, a biopsy, or removal.",
            "Which approach is appropriate depends entirely on the actual clinical diagnosis, the lesion's history, and the patient's overall health — this app cannot determine that.",
        ],
        "when_to_see_dermatologist": [
            "Any new or changing mole or lesion",
            "Asymmetry, irregular border, uneven color, or diameter growth (the common 'ABCDE' warning signs)",
            "Rapid growth over weeks to months",
            "Bleeding, oozing, or a sore that doesn't heal",
            "Persistent itching or pain in a lesion",
            "Any lesion you are simply unsure about — when in doubt, get it checked",
        ],
        "reliability_note": (
            "This result is a pattern-recognition output from an image model trained "
            "on a limited public dataset. It can be wrong in both directions — it "
            "may flag benign lesions, and it may miss lesions that need attention. "
            "Professional evaluation is recommended regardless of this result if you "
            "have any concern about a lesion."
        ),
    },
    "benign-pattern": {
        "summary": (
            "The model did not detect the visual patterns it associates with "
            "higher-risk lesions in the training data. This is reassuring as a "
            "screening signal, but it is not a clearance or a diagnosis."
        ),
        "what_happens_in_skin": (
            "Most skin marks — common moles, age spots, benign keratoses, "
            "small vascular marks — are harmless and simply reflect normal "
            "variation in skin. They can still change slowly over time as "
            "part of normal aging or sun exposure."
        ),
        "contributing_factors": [
            {"factor": "Normal skin variation", "note": "Most people have multiple benign marks; having them is common and expected."},
            {"factor": "Sun exposure over time", "note": "Can cause benign pigmentation changes (like age spots) that are cosmetic, not dangerous."},
            {"factor": "Genetics", "note": "Skin type and mole patterns are strongly inherited."},
        ],
        "avoid": [
            {"action": "Avoid assuming a benign screening result means no future monitoring is needed",
             "why": "Skin changes over months or years, and a screening result only reflects the image at this moment."},
            {"action": "Avoid excessive picking or irritation of any mark, even a benign one",
             "why": "Irritating a benign lesion can cause inflammation or scarring without any medical benefit."},
        ],
        "general_care": [
            {"action": "Continue routine sun protection",
             "why": "UV exposure is the most modifiable long-term factor in most skin changes."},
            {"action": "Do a periodic self-check of your skin (e.g. monthly)",
             "why": "Catching genuine changes early is the main way early evaluation happens for anyone."},
            {"action": "Keep a photo record of marks you want to track",
             "why": "Makes it easy to notice real change later, rather than relying on memory."},
        ],
        "management_approaches": [
            "No treatment is typically needed for common benign marks unless they bother you cosmetically or become symptomatic.",
            "If a benign-appearing mark later changes, professional re-evaluation is appropriate regardless of any earlier AI result.",
        ],
        "when_to_see_dermatologist": [
            "If this specific mark later changes in size, shape, color, or texture",
            "If it becomes itchy, painful, or starts bleeding",
            "As part of routine skin checks, especially with a personal or family history of skin cancer",
        ],
        "reliability_note": (
            "A 'benign-pattern' result reduces likelihood but does not rule out a "
            "concerning lesion — this model has not been clinically validated. If a "
            "mark has changed recently or concerns you, get it checked regardless of "
            "this result."
        ),
    },
}


def get_guidance_for_result(screening_label: str) -> dict:
    """Looks up guidance content for a model's screening_label. Raises
    instead of silently falling back, so a label typo or a future new class
    is caught immediately rather than showing wrong guidance."""
    if screening_label not in GUIDANCE_BY_SCREENING_RESULT:
        raise KeyError(
            f"No guidance content defined for screening result '{screening_label}'. "
            f"Known results: {list(GUIDANCE_BY_SCREENING_RESULT.keys())}"
        )
    return GUIDANCE_BY_SCREENING_RESULT[screening_label]


# ---------------------------------------------------------------------------
# 2. Skin Knowledge Center — general topics, independent of any scan result.
# ---------------------------------------------------------------------------
SKIN_KNOWLEDGE_CENTER = {
    "acne": {
        "what": "A condition where hair follicles become clogged with oil and dead skin cells, often involving bacteria and inflammation, producing whiteheads, blackheads, or inflamed pimples.",
        "common_causes": ["Excess oil (sebum) production", "Hormonal changes", "Clogged pores", "Certain medications", "Some cosmetic products"],
        "may_worsen_it": [
            {"action": "Picking or squeezing lesions", "why": "Increases inflammation and the risk of scarring."},
            {"action": "Over-washing or harsh scrubbing", "why": "Can damage the skin barrier and trigger more oil production."},
            {"action": "Heavy, pore-clogging (comedogenic) products", "why": "Can physically block follicles."},
        ],
        "general_care": [
            {"action": "Gentle, non-comedogenic cleansing twice daily", "why": "Removes excess oil without over-stripping skin."},
            {"action": "Consistent use of evidence-informed actives (e.g. salicylic acid, benzoyl peroxide) as tolerated", "why": "These have long-standing evidence for reducing acne lesions."},
        ],
        "when_to_see_doctor": ["Acne that scars", "No improvement after consistent over-the-counter care", "Painful, deep (cystic) lesions", "Sudden severe onset"],
    },
    "pigmentation": {
        "what": "Areas of skin that are darker (hyperpigmentation) or lighter (hypopigmentation) than surrounding skin, from causes like sun exposure, inflammation, or hormonal changes.",
        "common_causes": ["UV exposure", "Post-inflammatory marks after acne or injury", "Hormonal changes (e.g. melasma)", "Some medications"],
        "may_worsen_it": [
            {"action": "Unprotected sun exposure", "why": "UV light stimulates pigment-producing cells and can darken existing marks."},
            {"action": "Picking at healing skin", "why": "Re-injury tends to worsen post-inflammatory pigmentation."},
        ],
        "general_care": [
            {"action": "Daily broad-spectrum sunscreen", "why": "The single most effective way to prevent pigmentation from worsening."},
            {"action": "Gradual introduction of brightening ingredients (e.g. niacinamide, vitamin C) as tolerated", "why": "Can help even skin tone over time with consistent use."},
        ],
        "when_to_see_doctor": ["Rapidly spreading or asymmetric pigment changes", "Pigmentation associated with a changing mole", "No improvement with consistent sun protection over months"],
    },
    "dry_skin": {
        "what": "Skin lacking sufficient moisture or oil, often appearing flaky, rough, or tight.",
        "common_causes": ["Cold/dry weather", "Hot showers", "Harsh cleansers", "Aging skin", "Certain skin conditions (e.g. eczema)"],
        "may_worsen_it": [
            {"action": "Hot water and long showers", "why": "Strips natural oils from the skin barrier."},
            {"action": "Alcohol-heavy or fragranced products", "why": "Can further dehydrate and irritate compromised skin."},
        ],
        "general_care": [
            {"action": "Moisturize immediately after washing, while skin is still damp", "why": "Helps lock in moisture more effectively."},
            {"action": "Use a gentle, fragrance-free cleanser", "why": "Minimizes further barrier disruption."},
        ],
        "when_to_see_doctor": ["Persistent dryness despite consistent moisturizing", "Cracking, bleeding, or signs of infection", "Suspected underlying condition like eczema or psoriasis"],
    },
    "irritation": {
        "what": "Skin reacting to a physical, chemical, or environmental trigger with redness, itching, burning, or stinging.",
        "common_causes": ["Harsh products or fragrances", "Over-exfoliation", "Environmental factors (wind, cold, pollution)", "Allergic reactions"],
        "may_worsen_it": [
            {"action": "Continuing to use the suspected irritating product", "why": "Repeated exposure keeps re-triggering the reaction."},
            {"action": "Layering multiple active ingredients at once", "why": "Increases the chance of cumulative irritation."},
        ],
        "general_care": [
            {"action": "Simplify your routine to a gentle cleanser and moisturizer until skin settles", "why": "Reduces the number of possible triggers."},
            {"action": "Patch-test new products before full-face use", "why": "Catches a reaction on a small area before it affects your whole face."},
        ],
        "when_to_see_doctor": ["Irritation that doesn't improve after stopping likely triggers", "Swelling, blistering, or signs of a severe allergic reaction", "Recurrent irritation with no clear cause"],
    },
    "sun_damage": {
        "what": "Cumulative skin changes from UV exposure — including fine lines, pigmentation, texture changes, and increased risk of skin lesions over time.",
        "common_causes": ["Unprotected sun exposure over years", "Tanning bed use", "Living in high-UV climates without protection"],
        "may_worsen_it": [
            {"action": "Continued unprotected sun exposure", "why": "UV damage is cumulative and largely irreversible once it occurs."},
        ],
        "general_care": [
            {"action": "Daily broad-spectrum SPF 30+", "why": "The primary evidence-based way to prevent further damage."},
            {"action": "Protective clothing and shade during peak UV hours", "why": "Reduces cumulative exposure beyond what sunscreen alone covers."},
        ],
        "when_to_see_doctor": ["Any new or changing spot in sun-damaged skin", "Rough, persistent patches that don't heal (possible actinic keratosis)", "A personal or family history of skin cancer"],
    },
    "moles": {
        "what": "Common, usually benign, clusters of pigment-producing cells (melanocytes) that most people have in varying numbers.",
        "common_causes": ["Genetics", "Sun exposure", "Normal skin development"],
        "may_worsen_it": [
            {"action": "Repeated friction or irritation of a mole", "why": "Can cause inflammation, though this alone does not make a mole dangerous."},
        ],
        "general_care": [
            {"action": "Monthly self skin-checks using the ABCDE rule (Asymmetry, Border, Color, Diameter, Evolving)", "why": "Helps you notice genuine change early."},
            {"action": "Sun protection over moles like the rest of your skin", "why": "Reduces UV-related change over time."},
        ],
        "when_to_see_doctor": ["Any mole that is changing", "A mole that looks different from your other moles ('ugly duckling' sign)", "New moles appearing after age 30, especially if changing"],
    },
    "skin_lesions": {
        "what": "A general term for any area of skin that differs from the skin around it — includes a huge range of both benign and concerning findings.",
        "common_causes": ["Wide-ranging — infections, inflammation, benign growths, sun damage, and more"],
        "may_worsen_it": [
            {"action": "Self-diagnosing and self-treating without evaluation", "why": "Different causes need different management; treating the wrong thing can delay proper care."},
        ],
        "general_care": [
            {"action": "Photograph and date any lesion you're tracking", "why": "Objective record beats memory for judging change."},
        ],
        "when_to_see_doctor": ["Any lesion causing you concern", "Anything matching the warning signs listed under 'Moles' or 'Sun Damage'"],
    },
    "skin_barrier": {
        "what": "The outermost layer of skin that keeps moisture in and irritants/pathogens out. A 'damaged barrier' means this protective function is compromised.",
        "common_causes": ["Over-exfoliation", "Harsh cleansers", "Over-use of active ingredients", "Environmental stress"],
        "may_worsen_it": [
            {"action": "Continuing exfoliation/actives while the barrier is compromised", "why": "Prevents recovery and can deepen irritation."},
        ],
        "general_care": [
            {"action": "'Skin cycling' back to a minimal, gentle routine (cleanser, moisturizer, sunscreen only)", "why": "Gives the barrier time to recover before reintroducing actives."},
            {"action": "Ceramide-containing moisturizers", "why": "Ceramides are a natural component of a healthy barrier."},
        ],
        "when_to_see_doctor": ["Persistent burning, stinging, or peeling despite simplifying your routine", "Suspected allergic contact dermatitis"],
    },
    "sunscreen": {
        "what": "A product that filters or blocks UV radiation to protect skin from sun damage.",
        "common_causes": [],
        "may_worsen_it": [
            {"action": "Applying too little or infrequently", "why": "Reduces the actual protection factor far below the labeled SPF."},
        ],
        "general_care": [
            {"action": "Use broad-spectrum SPF 30+ daily, reapplied every ~2 hours with sun exposure", "why": "Broad-spectrum covers both UVA and UVB; reapplication matters because sunscreen degrades and rubs off."},
        ],
        "when_to_see_doctor": ["Persistent reaction to sunscreen ingredients (consider patch-testing alternatives)"],
    },
    "skincare_ingredients": {
        "what": "See the dedicated Ingredient Explainer (INGREDIENT_EXPLAINER below) for individual ingredients.",
        "common_causes": [],
        "may_worsen_it": [
            {"action": "Combining multiple strong actives (e.g. retinoids + AHAs + benzoyl peroxide) at once", "why": "Cumulative irritation risk is much higher than using them separately."},
        ],
        "general_care": [
            {"action": "Introduce one new active at a time, a few weeks apart", "why": "Makes it possible to identify which product causes any reaction."},
        ],
        "when_to_see_doctor": ["Persistent reaction despite careful, gradual introduction of products"],
    },
    "when_to_see_a_dermatologist": {
        "what": "General guidance on when a skin concern warrants professional evaluation rather than self-care alone.",
        "common_causes": [],
        "may_worsen_it": [],
        "general_care": [],
        "when_to_see_doctor": [
            "Any new or changing mole/lesion",
            "A sore that doesn't heal within a few weeks",
            "Persistent symptoms despite consistent home care",
            "Anything that concerns you — professional evaluation is always a reasonable choice",
        ],
    },
}

# ---------------------------------------------------------------------------
# 3. Ingredient Explainer — general skincare-ingredient education.
# ---------------------------------------------------------------------------
INGREDIENT_EXPLAINER = {
    "niacinamide": {
        "what_is_it": "A form of vitamin B3 used topically in skincare.",
        "commonly_used_for": "Improving the appearance of pores, uneven tone, and supporting the skin barrier.",
        "why_used": "Has evidence for helping regulate oil production and improving barrier function with regular use.",
        "potential_benefits": ["Reduced appearance of pores over time", "Improved tone evenness", "Generally well tolerated"],
        "potential_irritation": "Low for most people; occasional flushing at high concentrations for sensitive skin.",
        "who_should_be_cautious": "Generally well tolerated; those with known sensitivity to it should patch-test.",
        "commonly_combined_with": "Hyaluronic acid, ceramides; often used well alongside most other actives.",
    },
    "salicylic_acid": {
        "what_is_it": "A beta-hydroxy acid (BHA), oil-soluble exfoliant.",
        "commonly_used_for": "Acne-prone and oily skin, blackheads/whiteheads.",
        "why_used": "Penetrates into oily pores to help clear buildup and has anti-inflammatory properties.",
        "potential_benefits": ["Reduced clogged pores", "Reduced acne lesions with consistent use"],
        "potential_irritation": "Dryness or peeling, especially at higher concentrations or with over-use.",
        "who_should_be_cautious": "Very dry or sensitized skin; those already using other exfoliating actives.",
        "commonly_combined_with": "Moisturizers with ceramides/hyaluronic acid to offset dryness.",
    },
    "benzoyl_peroxide": {
        "what_is_it": "An antibacterial/anti-inflammatory ingredient used for acne.",
        "commonly_used_for": "Inflammatory acne.",
        "why_used": "Reduces acne-associated bacteria and inflammation.",
        "potential_benefits": ["Reduction in inflammatory acne lesions"],
        "potential_irritation": "Dryness, peeling, can bleach fabric/hair.",
        "who_should_be_cautious": "Sensitive or already-irritated skin; start with lower concentrations.",
        "commonly_combined_with": "Non-comedogenic moisturizer; avoid combining with retinoids in the same application to reduce irritation.",
    },
    "retinoids": {
        "what_is_it": "Vitamin A derivatives (e.g. retinol, adapalene, tretinoin) available over-the-counter and by prescription.",
        "commonly_used_for": "Acne, texture, fine lines, and overall cell turnover.",
        "why_used": "Well-established evidence for improving acne and photoaging over consistent long-term use.",
        "potential_benefits": ["Reduced acne", "Improved texture and tone over months of use"],
        "potential_irritation": "Dryness, peeling, sun sensitivity — common especially when starting out.",
        "who_should_be_cautious": "Pregnant or breastfeeding individuals should avoid — consult a doctor; sensitive skin should start low-frequency.",
        "commonly_combined_with": "Sunscreen (essential, due to increased sun sensitivity), gentle moisturizers; generally not combined with other strong exfoliants at the same time.",
    },
    "azelaic_acid": {
        "what_is_it": "A naturally occurring acid with anti-inflammatory and antibacterial properties.",
        "commonly_used_for": "Acne, rosacea-related redness, and pigmentation.",
        "why_used": "Multi-purpose evidence for both acne and pigment-evening effects, generally gentle.",
        "potential_benefits": ["Reduced acne", "Improved evenness of tone", "Reduced redness for some"],
        "potential_irritation": "Mild tingling initially for some users; generally one of the gentler actives.",
        "who_should_be_cautious": "Generally well tolerated across skin types.",
        "commonly_combined_with": "Most other actives; often recommended as a gentler alternative or addition.",
    },
    "vitamin_c": {
        "what_is_it": "An antioxidant (commonly L-ascorbic acid) used topically.",
        "commonly_used_for": "Brightening, antioxidant protection, supporting collagen production.",
        "why_used": "Evidence for reducing UV-related oxidative damage and improving tone when formulated/stored properly.",
        "potential_benefits": ["Brighter-looking skin", "Some antioxidant protection alongside sunscreen"],
        "potential_irritation": "Can sting or irritate sensitive skin, especially at high concentrations or low pH formulations.",
        "who_should_be_cautious": "Very sensitive skin; those combining with other strong actives.",
        "commonly_combined_with": "Sunscreen (complementary antioxidant protection); often used in the morning.",
    },
    "ceramides": {
        "what_is_it": "Lipids naturally found in skin that make up part of the skin barrier.",
        "commonly_used_for": "Supporting/restoring barrier function, especially in dry or compromised skin.",
        "why_used": "Directly replenishes a component the skin barrier is naturally made of.",
        "potential_benefits": ["Improved moisture retention", "Support during barrier recovery"],
        "potential_irritation": "Very low — one of the least irritating categories of ingredient.",
        "who_should_be_cautious": "Essentially anyone can use ceramide-containing moisturizers.",
        "commonly_combined_with": "Nearly everything — often paired with actives to offset their dryness.",
    },
    "hyaluronic_acid": {
        "what_is_it": "A humectant that attracts and holds water in the skin.",
        "commonly_used_for": "Hydration for most skin types.",
        "why_used": "Can hold many times its weight in water, helping skin feel plumper and more hydrated.",
        "potential_benefits": ["Improved surface hydration", "Generally suitable for all skin types"],
        "potential_irritation": "Very low; in very dry/low-humidity environments it can pull moisture from deeper skin if not sealed with a moisturizer.",
        "who_should_be_cautious": "Those in very dry climates should layer it under a moisturizer rather than use it alone.",
        "commonly_combined_with": "Virtually any other ingredient; often used as a hydration base layer.",
    },
    "ahas": {
        "what_is_it": "Alpha-hydroxy acids (e.g. glycolic acid, lactic acid) — water-soluble exfoliants.",
        "commonly_used_for": "Texture, tone, mild pigmentation, surface exfoliation.",
        "why_used": "Helps remove built-up dead skin cells to improve texture and tone over time.",
        "potential_benefits": ["Smoother texture", "More even tone with consistent use"],
        "potential_irritation": "Dryness, sun sensitivity, irritation with over-use.",
        "who_should_be_cautious": "Sensitive or already-irritated skin; those layering with other exfoliants.",
        "commonly_combined_with": "Daily sunscreen (essential), barrier-supportive moisturizers.",
    },
    "bhas": {
        "what_is_it": "Beta-hydroxy acids — primarily salicylic acid (see its own entry above).",
        "commonly_used_for": "Oily/acne-prone skin, blackheads.",
        "why_used": "Oil-soluble, so it can penetrate into pores more effectively than water-soluble AHAs.",
        "potential_benefits": ["Reduced clogged pores", "Reduced acne with consistent use"],
        "potential_irritation": "Dryness/peeling with over-use.",
        "who_should_be_cautious": "Very dry or sensitized skin.",
        "commonly_combined_with": "Non-comedogenic moisturizers; generally not combined with other strong exfoliants at once.",
    },
}
